// packages/react/src/components/WidgetPanel.tsx
import { useState, type ReactNode } from 'react';
import './WidgetPanel.css';

export interface WidgetPanelProps {
  title: string;
  /** @deprecated use canExpand */
  canCollapse?: boolean;
  canExpand?: boolean;
  canCollapseToTab?: boolean;
  /** @deprecated use initialExpanded */
  initialCollapsed?: boolean;
  initialExpanded?: boolean;
  /** Controlled expanded state */
  expanded?: boolean;
  /** @deprecated use expanded */
  collapsed?: boolean;
  headerActions?: ReactNode;
  children: ReactNode;
  onExpandedChange?: (expanded: boolean) => void;
  /** @deprecated use onExpandedChange */
  onCollapseChange?: (collapsed: boolean) => void;
  onCollapseToTab?: () => void;
}

export function WidgetPanel({
  title,
  canCollapse = true,
  canExpand,
  canCollapseToTab = false,
  initialCollapsed = false,
  initialExpanded = true,
  expanded: controlledExpanded,
  collapsed: controlledCollapsed,
  headerActions,
  children,
  onExpandedChange,
  onCollapseChange,
  onCollapseToTab,
}: WidgetPanelProps) {
  const allowExpand = canExpand ?? canCollapse;
  const initial = initialCollapsed ? false : initialExpanded;
  const [internalExpanded, setInternalExpanded] = useState(initial);

  const expanded =
    controlledExpanded ??
    (controlledCollapsed !== undefined ? !controlledCollapsed : internalExpanded);

  const toggleExpanded = () => {
    const next = !expanded;
    if (controlledExpanded === undefined && controlledCollapsed === undefined) {
      setInternalExpanded(next);
    }
    onExpandedChange?.(next);
    onCollapseChange?.(!next);
  };

  return (
    <section
      className={`wdg-widget-panel${expanded ? '' : ' wdg-widget-panel--contracted'}`}
    >
      <header className="wdg-widget-panel__header">
        <h2 className="wdg-widget-panel__title">{title}</h2>
        <span className="wdg-widget-panel__spacer" />
        {headerActions}
        {canCollapseToTab && (
          <button
            type="button"
            className="wdg-widget-panel__collapse"
            aria-label="Collapse to tab bar"
            onClick={() => onCollapseToTab?.()}
          >
            Tab
          </button>
        )}
        {allowExpand && (
          <button
            type="button"
            className="wdg-widget-panel__collapse"
            aria-label={expanded ? 'Contract panel' : 'Expand panel'}
            onClick={toggleExpanded}
          >
            {expanded ? '▴' : '▾'}
          </button>
        )}
      </header>
      {expanded && <div className="wdg-widget-panel__content">{children}</div>}
    </section>
  );
}

// packages/angular/src/lib/layout/widget-panel/widget-panel.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  signal,
} from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'wdg-widget-panel',
  standalone: true,
  imports: [MatCardModule, MatButtonModule, MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <mat-card class="wdg-widget-panel" [class.wdg-widget-panel--contracted]="!expanded()">
      <mat-card-header class="wdg-widget-panel__header">
        <mat-card-title>{{ title }}</mat-card-title>
        <span class="wdg-widget-panel__spacer"></span>
        <ng-content select="[headerActions]" />
        @if (canCollapseToTab) {
          <button
            mat-icon-button
            type="button"
            aria-label="Collapse to tab bar"
            (click)="collapseToTab.emit()"
          >
            <mat-icon>tab</mat-icon>
          </button>
        }
        @if (canExpand) {
          <button
            mat-icon-button
            type="button"
            [attr.aria-label]="expanded() ? 'Contract panel' : 'Expand panel'"
            (click)="toggleExpanded()"
          >
            <mat-icon>{{ expanded() ? 'expand_less' : 'expand_more' }}</mat-icon>
          </button>
        }
      </mat-card-header>

      <mat-card-content
        class="wdg-widget-panel__content"
        [class.wdg-widget-panel__content--hidden]="!expanded()"
      >
        <ng-content />
      </mat-card-content>
    </mat-card>
  `,
  styles: [
    `
      .wdg-widget-panel {
        display: flex;
        flex-direction: column;
        box-sizing: border-box;
        width: 100%;
        height: auto;
      }

      .wdg-widget-panel__header {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        flex-shrink: 0;
      }

      .wdg-widget-panel__spacer {
        flex: 1;
      }

      .wdg-widget-panel__content {
        overflow: auto;
      }

      .wdg-widget-panel__content--hidden {
        display: none;
      }

      .wdg-widget-panel--contracted .wdg-widget-panel__header {
        border-bottom: none;
      }
    `,
  ],
})
export class WidgetPanelComponent implements OnInit {
  @Input({ required: true }) title!: string;
  /** @deprecated use initialExpanded */
  @Input() canCollapse = true;
  @Input() canExpand = true;
  @Input() canCollapseToTab = false;
  /** @deprecated use initialExpanded */
  @Input() initialCollapsed = false;
  @Input() initialExpanded = true;
  @Output() expandedChange = new EventEmitter<boolean>();
  /** @deprecated use expandedChange */
  @Output() collapseChange = new EventEmitter<boolean>();
  @Output() collapseToTab = new EventEmitter<void>();

  protected readonly expanded = signal(true);

  ngOnInit(): void {
    const expanded = this.initialCollapsed ? false : this.initialExpanded;
    this.expanded.set(expanded);
  }

  protected toggleExpanded(): void {
    this.expanded.update(v => !v);
    this.expandedChange.emit(this.expanded());
    this.collapseChange.emit(!this.expanded());
  }
}
