// apps/demo-react/src/widgets/DemoTimerWidget.tsx
import { useEffect, useState } from 'react';
import type { WidgetLayoutItem } from '@ncs_software/widget-system';

export function DemoTimerWidget({ item }: { item: WidgetLayoutItem }) {
  const [seconds, setSeconds] = useState(0);

  useEffect(() => {
    const id = window.setInterval(() => setSeconds(s => s + 1), 1000);
    return () => window.clearInterval(id);
  }, []);

  return (
    <p style={{ margin: 0, fontSize: '1.25rem' }}>
      Elapsed: <strong>{seconds}s</strong> ({item.instanceId.slice(0, 8)}…)
    </p>
  );
}

// apps/demo-angular/src/app/widgets/demo-timer-widget.component.ts
import { Component, Input } from '@angular/core';
import type { WidgetLayoutItem } from '@ncs_software/widget-system';

@Component({
  selector: 'demo-timer-widget',
  standalone: true,
  template: `
    <p class="demo-timer">
      Elapsed: <strong>{{ seconds }}s</strong>
    </p>
  `,
  styles: [
    `
      .demo-timer {
        margin: 0;
        font-size: 1.25rem;
      }
    `,
  ],
})
export class DemoTimerWidgetComponent {
  @Input({ required: true }) item!: WidgetLayoutItem;
  protected seconds = 0;

  constructor() {
    setInterval(() => {
      this.seconds += 1;
    }, 1000);
  }
}
