// apps/demo-react/src/widgets/DemoNotesWidget.tsx
import { useEffect, useRef, useState } from 'react';
import type { WidgetConfig, WidgetMeta, WidgetState } from '@ncs_software/widget-system';
import { useWidgetStateService } from '@ncs_software/widget-system-react';

interface DemoNotesState {
  text: string;
}

export const demoNotesWidgetMeta: WidgetMeta = {
  widgetId: 'demo-notes',
  displayName: 'Notes',
  description: 'Simple notes widget for the demo workspace',
  minWidthPx: 320,
  canCollapse: true,
};

export interface DemoNotesWidgetProps {
  config: WidgetConfig;
  onStateChange?: (state: WidgetState<DemoNotesState>) => void;
}

export function DemoNotesWidget({ config, onStateChange }: DemoNotesWidgetProps) {
  const widgetStateService = useWidgetStateService();
  const [text, setText] = useState('');
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    let cancelled = false;

    widgetStateService
      .loadState<DemoNotesState>(config.widgetId, config.contextId)
      .then(saved => {
        if (!cancelled) {
          setText(saved?.payload.text ?? '');
        }
      });

    return () => {
      cancelled = true;
    };
  }, [config.widgetId, config.contextId, widgetStateService]);

  useEffect(() => {
    return () => {
      if (saveTimer.current) {
        clearTimeout(saveTimer.current);
      }
    };
  }, []);

  const scheduleSave = (payload: DemoNotesState) => {
    if (saveTimer.current) {
      clearTimeout(saveTimer.current);
    }
    saveTimer.current = setTimeout(() => {
      widgetStateService
        .saveState(config.widgetId, config.contextId, payload)
        .then(saved => onStateChange?.(saved));
    }, 2000);
  };

  return (
    <label className="demo-notes">
      <span className="demo-notes__label">Notes</span>
      <textarea
        className="demo-notes__field"
        rows={12}
        value={text}
        onChange={e => {
          const value = e.target.value;
          setText(value);
          scheduleSave({ text: value });
        }}
        placeholder="Type notes — state persists via WidgetStateService"
      />
    </label>
  );
}

// apps/demo-angular/src/app/widgets/demo-notes-widget.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  inject,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import type { WidgetConfig, WidgetMeta, WidgetState } from '@ncs_software/widget-system';
import { WidgetStateService } from '@ncs_software/widget-system-angular';

interface DemoNotesState {
  text: string;
}

@Component({
  selector: 'demo-notes-widget',
  standalone: true,
  imports: [FormsModule, MatFormFieldModule, MatInputModule],
  template: `
    <mat-form-field appearance="outline" class="demo-notes__field">
      <mat-label>Notes</mat-label>
      <textarea
        matInput
        rows="12"
        [ngModel]="text()"
        (ngModelChange)="onTextChange($event)"
        placeholder="Type notes — state persists via WidgetStateService"
      ></textarea>
    </mat-form-field>
  `,
  styles: [
    `
      .demo-notes__field {
        width: 100%;
      }
    `,
  ],
})
export class DemoNotesWidgetComponent implements OnInit, OnDestroy {
  static readonly widgetMeta: WidgetMeta = {
    widgetId: 'demo-notes',
    displayName: 'Notes',
    description: 'Simple notes widget for the demo workspace',
    minWidthPx: 320,
    canCollapse: true,
  };

  @Input({ required: true }) config!: WidgetConfig;
  @Output() stateChange = new EventEmitter<WidgetState<DemoNotesState>>();

  protected readonly text = signal('');

  private readonly widgetStateService = inject(WidgetStateService);
  private saveTimer: ReturnType<typeof setTimeout> | null = null;

  ngOnInit(): void {
    this.widgetStateService
      .loadState<DemoNotesState>(this.config.widgetId, this.config.contextId)
      .subscribe(saved => {
        this.text.set(saved?.payload.text ?? '');
      });
  }

  ngOnDestroy(): void {
    if (this.saveTimer) {
      clearTimeout(this.saveTimer);
    }
  }

  protected onTextChange(value: string): void {
    this.text.set(value);
    this.scheduleSave({ text: value });
  }

  private scheduleSave(payload: DemoNotesState): void {
    if (this.saveTimer) {
      clearTimeout(this.saveTimer);
    }
    this.saveTimer = setTimeout(() => {
      this.widgetStateService
        .saveState(this.config.widgetId, this.config.contextId, payload)
        .subscribe(saved => this.stateChange.emit(saved));
    }, 2000);
  }
}
