// packages/react/src/components/WorkspaceShell.tsx
import { useEffect, useState, type ReactNode } from 'react';
import type { WorkspaceConfig } from '@ncs_software/widget-system';
import { useWidgetStateService } from '../widget-state-context.js';
import { WorkspaceLayout } from './WorkspaceLayout.js';
import './WorkspaceShell.css';

export interface WorkspaceShellProps {
  workspaceId: string;
  defaultWorkspace?: Omit<WorkspaceConfig, 'id' | 'createdAt' | 'updatedAt'>;
  primaryPanel: ReactNode;
  secondaryPanel: ReactNode;
}

export function WorkspaceShell({
  workspaceId,
  defaultWorkspace,
  primaryPanel,
  secondaryPanel,
}: WorkspaceShellProps) {
  const widgetStateService = useWidgetStateService();
  const [workspace, setWorkspace] = useState<WorkspaceConfig | null>(null);

  useEffect(() => {
    let cancelled = false;

    const buildDefault = (): WorkspaceConfig => {
      const now = new Date();
      return {
        id: workspaceId,
        userId: defaultWorkspace?.userId ?? 'demo-user',
        name: defaultWorkspace?.name ?? 'Demo Workspace',
        contextType: defaultWorkspace?.contextType ?? 'general',
        contextId: defaultWorkspace?.contextId ?? null,
        panelOrder: defaultWorkspace?.panelOrder ?? 'primary-left',
        widgets: defaultWorkspace?.widgets ?? [],
        createdAt: now,
        updatedAt: now,
      };
    };

    widgetStateService
      .loadOrCreateDefault(workspaceId, buildDefault)
      .then(ws => {
        if (!cancelled) {
          setWorkspace(ws);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [workspaceId, defaultWorkspace, widgetStateService]);

  if (!workspace) {
    return <p className="wdg-workspace-shell__loading">Loading workspace…</p>;
  }

  return (
    <WorkspaceLayout
      workspaceId={workspace.id}
      primaryPanel={primaryPanel}
      secondaryPanel={secondaryPanel}
    />
  );
}

// packages/angular/src/lib/workspace/workspace-shell.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnInit,
  inject,
  signal,
} from '@angular/core';
import type { WorkspaceConfig } from '@ncs_software/widget-system';
import { WidgetStateService } from '../services/widget-state.service';
import { WorkspaceLayoutComponent } from '../layout/workspace-layout/workspace-layout.component';

@Component({
  selector: 'wdg-workspace-shell',
  standalone: true,
  imports: [WorkspaceLayoutComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (workspace(); as ws) {
      <wdg-workspace-layout [workspaceId]="ws.id">
        <div primaryPanel>
          <ng-content select="[primaryPanel]" />
        </div>
        <div secondaryPanel>
          <ng-content select="[secondaryPanel]" />
        </div>
      </wdg-workspace-layout>
    } @else {
      <p class="wdg-workspace-shell__loading">Loading workspace…</p>
    }
  `,
  styles: [
    `
      :host {
        display: block;
        height: 100%;
      }

      .wdg-workspace-shell__loading {
        padding: 1rem;
        margin: 0;
      }
    `,
  ],
})
export class WorkspaceShellComponent implements OnInit {
  @Input({ required: true }) workspaceId!: string;
  @Input() defaultWorkspace?: Omit<WorkspaceConfig, 'id' | 'createdAt' | 'updatedAt'>;

  protected readonly workspace = signal<WorkspaceConfig | null>(null);

  private readonly widgetStateService = inject(WidgetStateService);

  ngOnInit(): void {
    this.widgetStateService
      .loadOrCreateDefault(this.workspaceId, () => this.buildDefaultWorkspace())
      .subscribe(ws => this.workspace.set(ws));
  }

  private buildDefaultWorkspace(): WorkspaceConfig {
    const now = new Date();
    const defaults = this.defaultWorkspace;

    return {
      id: this.workspaceId,
      userId: defaults?.userId ?? 'demo-user',
      name: defaults?.name ?? 'Demo Workspace',
      contextType: defaults?.contextType ?? 'general',
      contextId: defaults?.contextId ?? null,
      panelOrder: defaults?.panelOrder ?? 'primary-left',
      widgets: defaults?.widgets ?? [],
      createdAt: now,
      updatedAt: now,
    };
  }
}
