// apps/demo-angular/src/app/widgets/demo-widget-host.component.ts
import { Component, Input, inject } from '@angular/core';
import type { WidgetLayoutItem } from '@ncs_software/widget-system';
import {
  WidgetPanelComponent,
  WorkspaceLayoutService,
} from '@ncs_software/widget-system-angular';
import { DemoNotesWidgetComponent } from '../widgets/demo-notes-widget.component';
import { DemoChecklistWidgetComponent } from '../widgets/demo-checklist-widget.component';
import { DemoTimerWidgetComponent } from '../widgets/demo-timer-widget.component';
import { DemoLinksWidgetComponent } from '../widgets/demo-links-widget.component';

@Component({
  selector: 'demo-widget-host',
  standalone: true,
  imports: [
    WidgetPanelComponent,
    DemoNotesWidgetComponent,
    DemoChecklistWidgetComponent,
    DemoTimerWidgetComponent,
    DemoLinksWidgetComponent,
  ],
  template: `
    <wdg-widget-panel
      [title]="titleFor(item)"
      [initialExpanded]="item.expanded"
      [canCollapseToTab]="true"
      (expandedChange)="onExpandedChange($event)"
      (collapseToTab)="onCollapseToTab()"
    >
      @switch (item.widgetId) {
        @case ('demo-notes') {
          <demo-notes-widget [config]="widgetConfig(item)" />
        }
        @case ('demo-checklist') {
          <demo-checklist-widget [config]="widgetConfig(item)" />
        }
        @case ('demo-timer') {
          <demo-timer-widget [item]="item" />
        }
        @case ('demo-links') {
          <demo-links-widget [item]="item" />
        }
      }
    </wdg-widget-panel>
  `,
})
export class DemoWidgetHostComponent {
  @Input({ required: true }) item!: WidgetLayoutItem;

  private readonly layoutService = inject(WorkspaceLayoutService);

  protected titleFor(item: WidgetLayoutItem): string {
    return this.layoutService.displayName(item.widgetId);
  }

  protected widgetConfig(item: WidgetLayoutItem) {
    return {
      widgetId: item.widgetId,
      position: 'primary' as const,
      contextId: item.contextId,
      collapsed: !item.expanded,
    };
  }

  protected onExpandedChange(expanded: boolean): void {
    this.layoutService.setExpanded(this.item.instanceId, expanded).subscribe();
  }

  protected onCollapseToTab(): void {
    this.layoutService.collapseToTab(this.item.instanceId).subscribe();
  }
}

// apps/demo-react/src/widgets/DemoWidgetHost.tsx
import type { WidgetLayoutItem } from '@ncs_software/widget-system';
import { WidgetPanel, useWorkspaceLayoutService } from '@ncs_software/widget-system-react';
import { DemoChecklistWidget } from './DemoChecklistWidget';
import { DemoNotesWidget } from './DemoNotesWidget';
import { DemoTimerWidget } from './DemoTimerWidget';
import { DemoLinksWidget } from './DemoLinksWidget';

export function DemoWidgetHost({ item }: { item: WidgetLayoutItem }) {
  const layoutService = useWorkspaceLayoutService();

  const widgetConfig = {
    widgetId: item.widgetId,
    position: 'primary' as const,
    contextId: item.contextId,
    collapsed: !item.expanded,
  };

  return (
    <WidgetPanel
      title={layoutService.displayName(item.widgetId)}
      expanded={item.expanded}
      canCollapseToTab
      onExpandedChange={expanded =>
        void layoutService.setExpanded(item.instanceId, expanded)
      }
      onCollapseToTab={() => void layoutService.collapseToTab(item.instanceId)}
    >
      {item.widgetId === 'demo-notes' && <DemoNotesWidget config={widgetConfig} />}
      {item.widgetId === 'demo-checklist' && (
        <DemoChecklistWidget config={widgetConfig} />
      )}
      {item.widgetId === 'demo-timer' && <DemoTimerWidget item={item} />}
      {item.widgetId === 'demo-links' && <DemoLinksWidget item={item} />}
    </WidgetPanel>
  );
}
